### ISSUE TITLE
Call it by its name

### ISSUE THREAD

**Issue by jlavelle** [mcneissue/purescript-snap#27]
[The spago file](https://github.com/jlavelle/purescript-snap/blob/master/spago.dhall#L8) says that this is `my-project`, but clearly this is `purescript-snap`. Fixing this could be a great first issue for the intrepid contributor!

**Comment by masaeedu** [comment]
Hello sir I am new babby programmer. Is this issue something I may help out with?

**Comment by masaeedu** [comment]
Wowie, my first merged pull request! I am both encouraged and enthused!
